jun-koyama-h/team_project

conflict.html

* mainがプロテクトされていて、ぷるりくでマージされるかテストです。

feat: protect main branch.

---

news-on-earth/package.json
news-on-earth/yarn.lock

fix: vulnerability.

---

news-on-earth/src/App.tsx
news-on-earth/src/views/SearchBox.tsx
news-on-earth/src/views/SearchResult.tsx

昨日教えていただいた方法を参考にして、ChatGPTにも協力してもらって、検索ボタンを押したら、検索結果ページに遷移するという処理を追加しました。
レビューをお願いできますでしょうか。

検索結果ページへの遷移を追加

---

api/src/index.ts

fix: news api.

---

news-on-earth/src/views/SearchPage.tsx

トップページでキーワードを入力すると、コンソールに日→英翻訳された結果が出力されます。
次は、この結果をNewsAPIに投げて検索結果を受け取る部分を作ります。

#40 feat: translated keyword to console

---

news-on-earth/src/views/SearchResult.module.css
news-on-earth/src/views/SearchResult.tsx

検索結果ページに地図を表示するようにしました。
デザインはまだ変更途中ですが、いったんcommitしました。

検索結果ページのデザインを変更（まだ途中です）

---

news-on-earth/src/views/SearchResult.tsx

キーワードを一時的にオプションに変更

---

news-on-earth/src/views/SearchPage.tsx
news-on-earth/src/views/SearchResult.tsx

GitHub Actionsでエラーとなったため未使用の定義を削除
https://github.com/jun-koyama-h/team_project/actions/runs/7443409232

GitHub Actionsでエラーとなったため修正

---

news-on-earth/src/views/SearchPage.tsx
news-on-earth/src/views/SearchResult.tsx

次回からはローカルで`yarn build`が通ることを確認してからpushします。

yarn buildでエラーが出たため再修正

---

api/src/index.ts

#52　feat: domainsパラメーターを/api/news/に追加

feat: domainsパラメーターを/api/news/に追加

---

api/src/index.ts
api/wrangler.toml

feat: workers kv.

---

news-on-earth/src/views/SearchBox.tsx
news-on-earth/src/views/SearchPage.module.css
news-on-earth/src/views/SearchPage.tsx

suggest apiの呼び出しを追加しました。
APIの戻り値のハンドリングはまだ作成できていませんが、いったんcommitしました。

suggest apiの呼び出しを追加

---

news-on-earth/src/views/SearchPage.tsx

#134 
ローカルで変更を確認できず・・壊したらごめんなさい。

feat: get articles from News API to console

---

news-on-earth/src/views/SearchBox.tsx

キーワードを全削除の×ボタン表示

---

news-on-earth/src/views/SearchBox.tsx

Reverts jun-koyama-h/team_project#166

Revert "キーワードを全削除の×ボタン表示"

---

news-on-earth/src/views/Map.tsx
news-on-earth/src/views/MapContainer.tsx

地図上の指定位置にピンを立てるようにしました。
それに伴って、ユーザの現在位置を取得する処理を削除しました（必要でしたら申し訳ありません。復活させます）。

地図上の指定位置にピンを立てるようにした

---

.github/workflows/cloudflare-workers.yml
api/babel.config.js
api/package.json
api/src/components/sum.ts
api/src/tests/sum.test.ts

feat: jest.

---

api/src/tests/sum.test.ts

fix: import jest.

---

api/src/index.ts

#173 domainsにドメインを加えて記事が取得できるか確認します

feat: add cnn.com to api domains

---

api/src/index.ts

fix: indian domain

---

news-on-earth/src/views/SearchPage.tsx

feat: use translationtojpn api for translation articles

---

news-on-earth/src/views/Map.tsx
news-on-earth/src/views/SearchResult.tsx

Reverts jun-koyama-h/team_project#202

Revert "検索結果ページの初期表示時に地図にピンを立てないように修正"

---

README.md

README追加　使用するメディア 12か国

---

news-on-earth/src/views/Test.tsx

feat: empty commit to try ci-cd

---

.github/workflows/development-workers.yml
api/wrangler.toml

本番環境と開発環境のKVを切り替えらるように修正

---

api/wrangler.toml

Reverts jun-koyama-h/team_project#212

Revert "wrangler.tomoにアカウントIDを追加"

---

.github/workflows/development-workers.yml
api/wrangler.toml

Reverts jun-koyama-h/team_project#211

Revert "本番環境と開発環境のKVを切り替えらるように修正"

---

news-on-earth/src/index.css
news-on-earth/src/views/SearchBox.tsx
news-on-earth/src/views/SearchPage.tsx

fix: suggest api.

---

news-on-earth/src/assets/clear.svg
news-on-earth/src/views/SearchBox.tsx
news-on-earth/src/views/SearchPage.module.css

検索ボックスに削除ボタンを入れた

---

.github/workflows/development-pages.yml
news-on-earth/babel.config.cjs
news-on-earth/jest.config.cjs
news-on-earth/package.json
news-on-earth/src/components/SimpleComponent.tsx
news-on-earth/src/test/SimpleComponent.test.tsx

ローカルでテストが通ったので、CIにはまだ組み込んでいませんがいったんコミットしました。

PagesにJestを追加

---

news-on-earth/package.json
news-on-earth/src/views/SearchPage.tsx
news-on-earth/yarn.lock

feat: modal dialog. #222
